Testing architecture
LesiaDorofiienko/playwright pull request #8
Opened 2023-12-03 18:44 UTC by LesiaDorofiienko

2023-12-03 20:37 UTC, sttaran requested changes
Group tests with files. It's hard to read all tests in one file

2023-12-03 20:37 UTC, sttaran commented on src/client/api-client.ts
> +  readonly users?: UserController;
you either have it or not

2023-12-03 20:37 UTC, sttaran commented on src/client/api-client.ts
> +  readonly users?: UserController;
if not then remove declaration

2023-12-03 20:37 UTC, sttaran commented on src/controllers/base.controller.ts
> +  constructor(
better use "object of parameters"

2023-12-03 20:37 UTC, sttaran commented on src/fixtures/index.ts
> +  clientWithNewUser: APIClient;
userData can have type, you know it's type

2023-12-03 20:37 UTC, sttaran commented on tests/api/brand-fixtures.spec.ts
> +    expect(response.status, "Status code should be 200").toEqual(200);
check response body

2023-12-03 20:37 UTC, sttaran commented on tests/api/brand-fixtures.spec.ts
> +    expect(response.status, "Status code should be 200").toEqual(200);
you should know what exactly it returns

2023-12-03 20:37 UTC, sttaran commented on tests/api/cars-controller.spec.ts
> +      expect(response.data.data[0]).toMatchObject(validCarData);
check all cars in response, otherwise you do not know what it returns

2023-12-06 17:53 UTC, LesiaDorofiienko commented on tests/api/brand-fixtures.spec.ts
> +    expect(response.status, "Status code should be 200").toEqual(200);
This is code from the lesson

2023-12-06 17:57 UTC, merged

2023-12-07 09:52 UTC, sttaran reviewed
1. Prepare state for tests in before* hooks and clear data in after* hooks
2. It is better to goup tests with test files. (createCar.specs.js, updateCar.specs.js etc)

2023-12-07 09:52 UTC, sttaran commented on src/fixtures/index.ts
> +  clientWithNewUser: APIClient;
probably you've forgotten this one

2023-12-07 09:52 UTC, sttaran commented on src/fixtures/index.ts
> +  clientWithNewUser: APIClient;
I meant do no use any
`(userData: any)`

2023-12-07 09:52 UTC, sttaran commented on tests/api/brands-controller.spec.ts
> +    // expect(response.data, "Valid brands should be returned").toEqual(VALID_BRANDS_RESPONSE_BODY)
why don't you check response body?

2023-12-07 09:52 UTC, sttaran commented on tests/api/cars-controller.spec.ts
> +    });
check all models by id